### ISSUE TITLE
gzip cannot open the connection tar (child): Cannot connect to C:

### ISSUE THREAD

**Issue by j-hartshorn** [andrie/miniCRAN#110] opened 2018-03-13 11:36 UTC
`sessionInfo()`

```
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)
...
other attached packages:
[1] miniCRAN_0.2.11
...
```

Running `makeRepo()` or `addPackage()` with `type = "source"' fails with the error message:

```
reading DESCRIPTION for package ‘base64enc’ failed with message:
  cannot open the connection
tar (child): Cannot connect to C: resolve failed

gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
```

From [this SO question](https://stackoverflow.com/questions/12823499/windows-command-line-tar-cannot-connect-to-d-resolve-failed-with-chef-knife), I think this is due to specifying the path in the form `"C:/Users/username/Desktop/miniCRAN"` which contains a `:`. Perhaps changing the gzip usage to use the `--force-local` argument would fix it?

**Comment by j-harts** [comment] 2018-03-13 11:37
Might be a duplicate of #95

**Comment by j-hartshorn** [comment] 2018-06-18 10:19
This is an issue with `tools::write_PACKAGES()`. The colon in the path name is misinterpreted by `tar`. If anyone else has a workaround for this, it would be greatly appreciated.

**Comment by andrie** [comment] 2018-06-22 08:06
Can you please  add a minimal reproducible example?

**Comment by j-hartshorn** [comment] 2018-06-22 08:41
For me, after copying `jsonlite_1.5.tar.gz` (or any source package) to the folder:
```
> tools::write_PACKAGES("C:/Users/JHartshorn/mre/src/contrib", type = "source")
tar (child): Cannot connect to C: resolve failed

gzip: stdin: unexpected end of file
/usr/bin/tar: Child returned status 128
/usr/bin/tar: Error is not recoverable: exiting now
reading DESCRIPTION for package ‘jsonlite’ failed with message:
  cannot open the connection
```

The problem is the version of `tar`:
```
> Sys.which("tar")
                                   tar 
"C:\\PROGRA~1\\Git\\usr\\bin\\tar.exe" 
```

If I remove `Git\\usr\\bin` from my `PATH` we're golden. This is an issue with my environment and not R or miniCRAN. Apologies for taking your time, but hopefully this will help someone else having the same problem in the future.

FYI
```
C:\Users\JHartshorn>git --version
git version 2.16.1.windows.4
```

**Comment by andrie** [comment] 2018-06-22 08:54
Thanks for the clarification!

**Closed** 2018-06-22 08:54 UTC
Labels: wontfix
