### ISSUE TITLE
Wrong contrib url for Mac binary packages

### ISSUE THREAD

**Issue by miguelalba** [andrie/miniCRAN#121] opened 2019-05-22 16:53 UTC
Hi! I have been using miniCRAN for a while and I am happy with it but I have this severe issue on Mac. I think it was already reported on https://github.com/andrie/miniCRAN/issues/90 which is closed.

When I try to use miniCRAN on R higher than 3.2 it fails to find the packages. For example, for 3.5:
```R
> pkgDep(c('tidyverse'), type='mac.binary')
Warning: unable to access index for repository https://cloud.r-project.org/bin/macosx/contrib/3.5:
  cannot open URL 'https://cloud.r-project.org/bin/macosx/contrib/3.5/PACKAGES'
Error in pkgDep(c("tidyverse"), type = "mac.binary") : 
  Unable to retrieve available packages from CRAN
```

The url https://cloud.r-project.org/bin/macosx/contrib/3.5/PACKAGES is not accessible. Under https://cloud.r-project.org/bin/macosx/contrib/ there are only packages for R 3.0, 3.1 and 3.2. At https://cran.rstudio.com/bin/macosx/el-capitan/contrib/ the packages for 3.4, 3.5 and 3.6 are available.

For Mac I have been sticking to R 3.0 so I could use miniCRAN while on Windows I could use 3.4. This is troublesome as some new packages do not have binaries on 3.0. I would like to use the same version on Mac and Windows. I ignore whether this has been fixed and the miniCRAN in CRAN is outdated?

**Comment by andrie** [comment] 2019-07-01 07:42
I think this is a duplicate of #111 that has been fixed already.

**Closed** 2019-07-09 14:10 UTC
Labels: duplicate
