### ISSUE TITLE
Rversion documentation mismatch

### ISSUE THREAD

**Issue by wildintellect** [andrie/miniCRAN#114] opened 2018-09-17 21:40 UTC
The makeRepo and addPackage documentation differ in how they describe the Rversion argument.

* addPackage
> Version of R. Can be specified as a character string with the two digit R version, e.g. "3.1". Defaults to R.version
* makeRepo
> List with two named elements: major and minor. If not supplied, defaults to system version of R, using R.version. Only used if type is not "source"

In testing I found the addPackage variant appears to be true for both functions, a character string "3.5", trying to use list(major=3,minor=5) threw errors. Can you please verify which syntax is accepted and update the docs to be consistent.

**Comment by sfweller** [comment] 2018-09-17 22:32
I am unable to reproduce the problem - I tried it with both addPackage() and makeRepo() -  are you using 'type=source'?  The online help mentions that Rversion does not work if type is set to 'source'....

If that is not the issue, can you please provide a short piece of reproduce code?

Thanks.

**Comment by wildintellect** [comment] 2018-09-17 22:49
It's not a code issue, but a documentation clarification:
```
library(miniCRAN)

testpkg <- "animation"
version <- "3.5"
versionlist <- list(major=3,minor=5)
types <- c("source","win.binary", "mac.binary.el-capitan")
dir.create("test")

#Works
makeRepo(pkgDep(testpkg), path="test",download=TRUE,type=types[2],writePACKAGES = TRUE,Rversion=version)
#Fails
makeRepo(pkgDep(testpkg), path="test",download=TRUE,type=types[2],writePACKAGES = TRUE,Rversion=versionlist)
```

**Comment by sfweller** [comment] 2018-09-17 22:58
Thanks for the feedback - we will update the documentation.

**Comment by andrie** [comment] 2019-06-30 20:58
Thanks, once again, for the report.  I have now fixed this in the dev version of the package.

**Closed** 2020-07-09 18:29 UTC
Labels: bug
