### ISSUE TITLE
Add packages to repository from GitHub (or other remotes) 

### ISSUE THREAD

**Issue by szimmer** [andrie/miniCRAN#143] opened 2021-07-16 14:37 UTC
I use miniCRAN to create a repository for a work environment where I have no internet. I use FTP to move my repository from my computer with internet over to the computer without internet. However, I'd like to add some packages from GitHub as well. This would be a nice feature rather than just getting packages from CRAN to either get packages that are only on GitHub or to get a feature that is on a development version of a package but not yet on CRAN.

**Comment by achubaty** [comment] 2021-07-16 14:55
duplicate of #50

**Closed by achubaty** 2021-07-16 14:55 UTC
