### ISSUE TITLE
building a miniCRAN 3.4 using R 3.6

### ISSUE THREAD

**Issue by Courvoisier13** [andrie/miniCRAN#129] opened 2019-10-28 16:27 UTC
I am using 3.6.1 and building a miniCRAN for R 3.4.4.

The new packages get added correctly and build a miniCRAN for R 3.4.4 correctly. However, when trying to install packages from the miniCRAN using the R 3.4.4 I get the error 

```
   Warning in install.packages :
    unable to access index for repository https://cran.rstudio.com/src/contrib:
    cannot open URL 'https://cran.rstudio.com/src/contrib/PACKAGES'

  Installing packages into ‘D:/libraries/R/libraries’ (as ‘lib’ is unspecified)
  Error in install.packages : cannot read workspace version 3 written by R 3.6.1; need R 3.5.0 or newer
```

I found the issue and it was the index stored as RDS version 3

```
  > readRDS("path/miniCRAN3.4/bin/windows/contrib/3.4/PACKAGES.rds")
  Error in readRDS("path/miniCRAN3.4/bin/windows/contrib/3.4/PACKAGES.rds") : 
    cannot read workspace version 3 written by R 3.6.1; need R 3.5.0 or newer
```

So I read the file in R 3.6, and overwrote it with `writeRDS(, version = 2)` and that solved the issue and I was able to install the packages in R 3.4.

So miniCRAN puts the right version of the libraries in the folder, but the index is an `.rds` and that is no longer compatible by default across R=<3.5 to R>=3.6

**Comment by achubaty** [comment] 2019-12-17 16:42
we are using `write_packages` as a wrapper for `tools::write_PACKAGES` to create the PACKAGES files. To work around this (within `write_packages`) using the approach suggested above, we would need to add an argument to pass in the `Rversion`.

**Comment by Courvoisier13** [comment] 2019-12-18 09:24
Hi, I actually solved the issue by setting env variable R_DEFAULT_SAVE_VERSION = 2 and R_DEFAULT_SERIALIZE_VERSION = 2. This way the .rds gets saved as version 2 (pre R 3.5). It's not ideal but it works while the team makes the switch.

**Comment by achubaty** [comment] 2019-12-19 16:03
@andrie we should add this to an example/vignette. I'll add it to my to do list, but I don't know when I'll get to it.

**Comment by andrie** [comment] 2020-07-12 15:26
I'm adding an `r_version` argument to `write_packages`.  (Now in the process of fixing the errors this introduces!)

**Comment by lucazav** [comment] 2022-11-20 10:04
I've just created a miniCRAN repository for an offline installation of R 3.4.4 using R 4.2.2. I installed the dev version of miniCRAN to be sure that the upon mentioned commit was included (its version is 0.2.16.9000). Here the code to create the repository using R 4.2.2:

```
library("miniCRAN")

# Reference the CRAN 0-Clud mirror
CRAN_mirror <- c(CRAN = "https://cloud.r-project.org")

# Declare the packages' destination folder in your local machine
# and create it
local_repo <- "C:/miniCRAN_R344"
dir.create(local_repo)

# Declare the packages you want to install (they can be more than one)
pkgs_needed <- c("ggplot2")

# Reference the package dependencies and add them to the packages declaration
pkgs_with_dependencies <- pkgDep(pkgs_needed, repos = CRAN_mirror)

# Download all packages with version compatible with the engine R 3.4.4 
makeRepo(pkgs_with_dependencies, path = local_repo,
         repos = CRAN_mirror,
         type = "win.binary",
         Rversion = "3.4.4")
```

When trying to install packages in R 3.4.4, I'm getting the following error:

>  Error in readRDS(dest) : 
>   cannot read workspace version 3 written by R 4.2.2; need R 3.5.0 or newer

Any hint, please?

**Comment by andrie** [comment] 2022-11-20 16:22
That commit was merged a long time ago, but it's clear that it didn't solve the root cause.

As a workaround I suggest you either use R-3.5 or earlier to create the miniCRAN, or use the advice earlier in this thread (https://github.com/andrie/miniCRAN/issues/129#issuecomment-566948376)

**Comment by andrie** [comment] 2022-11-24 17:16
The earlier supposed "fix" that I wrote didn't work at all.  I also couldn't get the proposed workaround to work as expected.

After some experimentation, I realised it's quite trivial to use `tools::write_PACKAGES()`  to write the `.rds` file, then read it into memory and write it out again, but this time using `version = 2`.

I have this working in my local main branch and will commit this soon.

**Comment by andrie** [comment] 2024-03-24 18:41
Can we close this now?

**Closed** 2024-03-28 20:56 UTC
Labels: Resolved in branch
